=== emontesdeoc/1DAWB/HTML/Tercer trimestre/XML/Ejercicios schemas/Ejercicio schemas/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="alumno" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="edad" type="xs:string" minOccurs="0"/>
        <xs:element name="nota">
          <xs:simpleType>
            <xs:union memberTypes="decilaldos nopresentado"/>
          </xs:simpleType>
        </xs:element>
        <xs:element name="comentario" type="xs:string" minOccurs="0"/>
        <xs:element ref="direccion" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="dni" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="calle" type="xs:string"/>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="provincia" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="decilaldos">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="nopresentado">
    <xs:restriction base="xs:string">
      <xs:pattern value="No presentado"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== emontesdeoc/1DAWB/HTML/Tercer trimestre/XML/Ejercicios schemas/Ejercicio schemas/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio2.xsd">
  <alumno dni="42289654X">
    <nombre>Emiliano</nombre>
    <apellidos>Montesdeoca</apellidos>
    <nota>5.62</nota>
    <comentario>Hola</comentario>
  </alumno>
  <alumno dni="63969852X">
    <nombre>Yaco</nombre>
    <apellidos>Aymediacoan</apellidos>
    <edad>16</edad>
    <nota>6.66</nota>
    <direccion>
      <calle>Calle Fuente</calle>
      <numero>4.66</numero>
      <ciudad>Jabugo</ciudad>
      <provincia>Huelva</provincia>
    </direccion>
  </alumno>
  <alumno dni="255165615X">
    <nombre>Saulo</nombre>
    <apellidos>Saulini</apellidos>
    <edad>16</edad>
    <nota>No presentado</nota>
    <comentario>Hola</comentario>
    <direccion>
      <calle>Calle Fuente</calle>
      <numero>4</numero>
      <ciudad>Jabugo</ciudad>
      <provincia>Huelva</provincia>
    </direccion>
  </alumno>
</alumnos>
