=== emontesdeoc/1DAWB/HTML/Tercer trimestre/XML/Ejercicios schemas/Ejercicio schemas/ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="alumno" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="edad" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="15"/>
              <xs:maxInclusive value="75"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="nota">
          <xs:simpleType>
            <xs:union memberTypes="nopresentado nota_values"/>
          </xs:simpleType>
        </xs:element>
        <xs:element name="comentario" type="xs:string" minOccurs="0"/>
        <xs:element ref="direccion" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="dni" type="DNI" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="calle" type="calle"/>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="ciudad" type="xs:string"/>
        <xs:element name="codigopostal" type="cp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="nopresentado">
    <xs:restriction base="xs:string">
      <xs:enumeration value="No presentado"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="cp">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{5}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="calle">
    <xs:restriction base="xs:string">
       <xs:maxLength value="18"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="nota_values">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DNI">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{7,8}[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== emontesdeoc/1DAWB/HTML/Tercer trimestre/XML/Ejercicios schemas/Ejercicio schemas/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
  <alumno dni="1234567B">
    <nombre>Emiliano</nombre>
    <apellidos>Montesdeoca</apellidos>
    <nota>5.62</nota>
    <comentario>Hola</comentario>
  </alumno>
  <alumno dni="12345678X">
    <nombre>Yaco</nombre>
    <apellidos>Aymediacoan</apellidos>
    <edad>16</edad>
    <nota>9</nota>
    <direccion>
      <calle>Calle Fuente</calle>
      <numero>4.66</numero>
      <ciudad>Jabugo</ciudad>
      <codigopostal>38635</codigopostal>
    </direccion>
  </alumno>
  <alumno dni="1234567X">
    <nombre>Saulo</nombre>
    <apellidos>Saulini</apellidos>
    <edad>16</edad>
    <nota>No presentado</nota>
    <comentario>Hola</comentario>
    <direccion>
      <calle>Calle Fuente</calle>
      <numero>4</numero>
      <ciudad>Jabugo</ciudad>
      <codigopostal>38111</codigopostal>
    </direccion>
  </alumno>
</alumnos>
